name: Reusable - Lint & Test

on:
  workflow_call:
    inputs:
      node-version:
        description: Node version to use
        required: false
        default: '20'
        type: string

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs['node-version'] }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm test
