name: CI - Compile Android

on:
  workflow_run:
    workflows: [ "CI - Lint and Test" ]   # must match the 'name:' of the lint/test workflow
    types: [ completed ]

# Cancel outdated runs on same branch/PR to save minutes
concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch || github.ref }}
  cancel-in-progress: true

jobs:
  compile-android:
    # Gate on success of the upstream workflow
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      # Checkout the exact commit that passed lint/test
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # Generate android/ from Expo config & config-plugins (CNG)
      - name: Expo prebuild (Android)
        env:
          EXPO_NO_INTERACTIVE: '1'
        run: npx expo prebuild --platform android --non-interactive
        # Expo CNG generates native projects on demand. Do not commit android/. (docs)

      # JDK 17 is required by modern Android Gradle Plugin 8.x
      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      # Gradle cache & optimal config on GHA
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Compile-only: fail fast on Java/Kotlin errors (faster than assemble)
      - name: Compile Android sources (Debug)
        working-directory: android
        run: |
          chmod +x ./gradlew
          ./gradlew :app:compileDebugSources --build-cache || \
          ./gradlew :app:compileDebugKotlin :app:compileDebugJavaWithJavac --build-cache
